name: Build & Push Docker Image to GHCR

on:
  push:
    branches: ['**']  # Trigger on all branches

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name and convert to lowercase
        shell: bash
        run: |
          # Extract branch name from GITHUB_REF
          if [[ "${{ github.ref }}" == refs/heads/* ]]; then
            BRANCH_NAME="${{ github.ref_name }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi
          
          # Convert to lowercase and sanitize for Docker tag
          BRANCH_TAG=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g')
          echo "BRANCH_TAG=$BRANCH_TAG" >> $GITHUB_ENV
          echo "Branch tag: $BRANCH_TAG"

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.BRANCH_TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
